name: CD Prod Pipeline

on:
  push:
    branches:
      - prod

jobs:
  security_scan_before_deploy:
    name: Security Scan Before Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev

      - name: Run Trivy scan before deploy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH

  deploy_prod:
    name: Deploy on runner_prod
    runs-on: runner_prod
    needs: security_scan_before_deploy

    steps:
      - name: Pull Docker image on prod runner
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev

      - name: Stop old container if exists
        run: docker stop intranet-prod || true

      - name: Remove old container if exists
        run: docker rm intranet-prod || true

      - name: Run new container
        run: docker run -d -p 8081:80 --name intranet-prod ${{ secrets.DOCKERHUB_USERNAME }}/intranet-newdeal:dev