name: Deploy to Kubernetes

on:
  push:
    branches:
      - k8s

jobs:
  deploy_k8s:
    name: Deploy on Kubernetes
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify kubectl
        shell: powershell
        run: kubectl version --client

      - name: Apply Deployment
        shell: powershell
        run: kubectl apply -f k8s/deployment.yaml

      - name: Apply Service
        shell: powershell
        run: kubectl apply -f k8s/service.yaml

      - name: Check pods
        shell: powershell
        run: kubectl get pods

      - name: Check services
        shell: powershell
        run: kubectl get svc

      - name: Port-forward and test application
        shell: powershell
        run: |
          Start-Process -NoNewWindow -FilePath "kubectl" -ArgumentList "port-forward service/intranet-newdeal-service 8080:80"
          Start-Sleep -Seconds 10
          try {
            Invoke-WebRequest -Uri "http://localhost:8080" -UseBasicParsing
            Write-Host "Application accessible !"
          } catch {
            Write-Error "Application non accessible !"
            exit 1
          }